version: 2
jobs:
  build:
    environment:
      TERM: 'dumb'
      ANDROID_HOME: '/home/ubuntu/android-sdk'
      ANDROID_NDK_REPOSITORY: "/home/ubuntu/android-ndk"
      JVM_OPTS: -Xmx3200m
    docker:
      - image: circleci/android:api-27-alpha
    steps:
      - checkout
      - run:
          name: Set up keys
          command: "[ -n \"$KEY\" ] && openssl aes-256-cbc -d -in scripts/setup-keys.enc -k $KEY >> gradle.properties || true"
      - run:
          name: Unset key
          command: "export KEY=\"<unset>\""
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "gradle.properties" }}
      - run:
          name: Install Buck Dependencies (TODO: Move this to Docker container)
          command: "apt-get update -qq && apt-get install -y ant"
      - run:
          name: Set up Buck and Android
          command: |
            if [[ ! -e $HOME/buck ]]; then git clone https://github.com/facebook/buck.git $HOME/buck; fi
            export PATH="$HOME/buck/bin:$PATH"
            cd $HOME/buck && ant
            buck --version
            source scripts/circle-ci-android-setup.sh && installAndroidSDK
            buck fetch //...
      - run:
          name: Gradle Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Buck Dependencies
          command: buck fetch //...
      - save_cache:
          paths:
            - ~/.gradle
            - ~/buck
            - ~/android-sdk
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "gradle.properties" }}
      - run:
          name: Run Tests
          command: |
            buck build sample
            buck build sample-barebones
            buck build sample-codelab
            buck test litho-it/src/test/...
            buck test litho-it-powermock/src/test/...
            ./gradlew test
            ./gradlew :sample-kotlin:assembleDebug
      - run:
          name: Publish Snapshot
          command: scripts/circle-ci-publish-snapshot.sh
